### ISSUE TITLE
Implement a way to get recent reitit builds from their master branch

### ISSUE THREAD

**Issue by scottlowe** [Swirrl/catql-prototype#38]

**Comment by rosado** [comment]
@RickMoynihan I'm trying to deploy reitit jars to s3://swirrl-jars/releases/ (using https://github.com/s3-wagon-private/s3-wagon-private plugin) but I don't have write permissions.

**Comment by RickMoynihan** [comment]
Done

**Comment by rosado** [comment]
I forked reitit and created a branch: https://github.com/Swirrl/reitit/tree/openapi-dev 

Only reason we need this branch is convenience of having the config for deployment to our private jar repo in there.

I didn't commit changes for updated version, because all that can be done with the following:

```
# set the version
./scripts/set-version "0.6.0-tpx-SNAPSHOT"

# install locally 
./scripts/lein-modules install

# deploy to S3
./scripts/lein-modules deploy private
```

**Comment by RickMoynihan** [comment]
Cool, so what are the deployed artifact names?  

`metosin/reitit {:mvn/version "0.6.0-tpx-SNAPSHOT}`?

**Comment by rosado** [comment]
Yes
